### PR TITLE
roundup() -> ceil(), for consistency with the existing floor()

### PR DESCRIPTION
**Pull request by felicialim**
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/iamf/pull/628.html" title="Last updated on Jul 12, 2023, 6:18 PM UTC (6ea66ea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/iamf/628/f047a0f...6ea66ea.html" title="Last updated on Jul 12, 2023, 6:18 PM UTC (6ea66ea)">Diff</a>

### CODE REVIEW

**Comment by felicialim** [comment]
Also happy to change floor() to rounddown() instead if there is a preference for that.

**Comment by sunghee-hwang** [comment]
@felicialim, how about making PR #627, #628, #630, and #631 as one single PR or fully separated ones?

From past experience, we had lost something during the merging of multiple PRs complicating each other so we should create another PR to fix it.

**Comment by sunghee-hwang** [comment]
This PR is merged into PR https://github.com/AOMediaCodec/iamf/pull/630.

@felicialim, please close this PR after checking it is properly implemented into PR https://github.com/AOMediaCodec/iamf/pull/630.

**Comment by felicialim** [comment]
Looks good so I'm closing this PR

**Pull request closed without merging**
