### PR TITLE
Fix #460, updated codecs parameter string

### LINKED ISSUE #460: Consider adding profile_compatible to codecs string.
https://github.com/AOMediaCodec/iamf/pull/453#discussion_r1218673740

### PR DESCRIPTION
**Pull request by sunghee-hwang**
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/iamf/pull/506.html" title="Last updated on Jun 28, 2023, 10:29 PM UTC (8686437)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/iamf/506/3318721...8686437.html" title="Last updated on Jun 28, 2023, 10:29 PM UTC (8686437)">Diff</a>

### CODE REVIEW

**Review by tdaede — APPROVED** [review]

**Comment by cconcolato** [comment]
`Codecs` should be spelled lower case `codecs`

**Comment by cconcolato** [comment]
The sentence 
```
The codecs parameter string for the AOM IA codec SHALL be
```
uses "AOM IA codec" which is not really defined.

**Comment by cconcolato** [comment]
Also, generally, I think the text should be improved. RFC 6381 (and other derived specs) indicates that the parameter is made of elements ("Each value consists of one or more dot-separated elements"). The ISOBMFF part says:
> For the ISO Base Media File Format, and the QuickTime movie file
   format, the first element of a 'codecs' parameter value is a sample
   description entry four-character code as registered by the MP4
   Registration Authority [[MP4RA](https://datatracker.ietf.org/doc/html/rfc6381#ref-MP4RA)].  Values are case sensitive.

This specification should say:
- Per RFC6381 and ISOBMFF, the first element of the codecs parameter string is `iamf`
- The second element indicates the primary_profile
- The 3rd element indicates the additional_profile
- The 4th element and any additional elements, if any, shall be the elements of the codecs parameter string if that stream was carried in its own track (i.e. not encapsulated in IAMF).

**Review by cconcolato — CHANGES_REQUESTED** [review]
See the "conversation" tab for comments

**Comment by cconcolato** [comment]
> * The 4th element and any additional elements, if any, shall be the elements of the codecs parameter string if that stream was carried in its own track (i.e. not encapsulated in IAMF).

In particular, for AAC the spec says:
> iamf.IAMF-specific-needs.mp4a.40.2

but `40.2` is a specific example. There could be other values like `40.5`.

**Comment by sunghee-hwang** [comment]
> > * The 4th element and any additional elements, if any, shall be the elements of the codecs parameter string if that stream was carried in its own track (i.e. not encapsulated in IAMF).
> 
> In particular, for AAC the spec says:
> 
> > iamf.IAMF-specific-needs.mp4a.40.2
> 
> but `40.2` is a specific example. There could be other values like `40.5`.

I know that '40.2' stands for AAC-LC. What does '40.5' stand for?

**Comment by tdaede** [comment]
With the new way the example is written, it no longer specifies 40.2 explicitly, though I think in practice, only 40.2 would be used as the spec is limited to AAC-LC.

**Pull request merged**
