### PR TITLE
Recover lost commits during rebase.

### PR DESCRIPTION
**Pull request by felicialim**
- https://github.com/AOMediaCodec/iamf/commit/8c471606d2b98f274949eb9503f25f73267b4927
- https://github.com/AOMediaCodec/iamf/pull/625/commits/7ebb93b9a3c6f82ab6166dc714ea2d97f4eb8155

***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/iamf/pull/651.html" title="Last updated on Jul 19, 2023, 10:34 AM UTC (7d215e0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/iamf/651/a5659f2...7d215e0.html" title="Last updated on Jul 19, 2023, 10:34 AM UTC (7d215e0)">Diff</a>

### CODE REVIEW

**Comment by sunghee-hwang** [comment]
782b186 should be 782b18b


Please refer to that I have checked from PR #611 up to PR #636.

**Comment by sunghee-hwang** [comment]
782b186 should be 782b18b

Please refer to that I have checked from PR #611 up to PR #636.

**Comment by sunghee-hwang** [comment]
FYI, I have checked from PR #611 to PR #643.

**Comment by felicialim** [comment]
Thanks for catching these! LGTM

**Review by tdaede — APPROVED** [review]

**Pull request merged**
